version: '3.8'

services:
  app-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://localhost:3000

  app-test:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=test
    command: npm run test

  app-demo:
    build:
      context: .
      target: production
    ports:
      - '8081:80'
    environment:
      - NODE_ENV=demo

  app-prod:
    build:
      context: .
      target: production
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    restart: always
