version: '3.8'

services:
  app-dev:
    build:
      context: .
      target: build-stage
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
    command: npm run dev

  app-test:
    build:
      context: .
      target: build-stage
    environment:
      - NODE_ENV=test
    command: npm run test

  app-demo:
    build:
      context: .
    ports:
      - '8081:80'
    environment:
      - NODE_ENV=demo
    depends_on:
      - app-dev

  app-prod:
    build:
      context: .
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    restart: always
